### ISSUE TITLE
[AIRFLOW-3333] New features enable transferring of files or data from GCS to a SFTP remote path and SFTP to GCS path.

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#121]
Hello,

Here is an ticket related to GCP on Jira:
https://issues.apache.org/jira/browse/AIRFLOW-3333

Lots of love

- [x] [[AIRFLOW-5717] Add get_tree_map method to SFTPHook](https://github.com/apache/airflow/pull/6387)
- [x] [[AIRFLOW-5707] Add type annotations to SFTPHook](https://github.com/apache/airflow/pull/6378)
- [x] [[AIRFLOW-5696] GoogleCloudStorageToSFTPOperator](https://github.com/apache/airflow/pull/6366)
- [x] [[AIRFLOW-5665] Add path_exists method to SFTPHook]()
- [x] [[AIRFLOW-5718] Add SFTPToGoogleCloudStorageOperator](https://github.com/apache/airflow/pull/6393)
- [x] [[AIRFLOW-5807] Move SFTP from contrib to providers. Depends on [AIRFLOW-6059]](https://github.com/apache/airflow/pull/6464)

**Comment by nuclearpinguin** [comment]
Duplicated and closed in:
https://issues.apache.org/jira/browse/AIRFLOW-3429

**Comment by TobKed** [comment]
Ongoing.
PRs already created and merged:
https://github.com/apache/airflow/pull/6387
https://github.com/apache/airflow/pull/6378
https://github.com/apache/airflow/pull/6366
https://github.com/apache/airflow/pull/6344
PRs in progress:
https://github.com/apache/airflow/pull/6393
https://github.com/PolideaInternal/airflow/pull/399

**Comment by mik-laj** [comment]
Is it done?

**Comment by TobKed** [comment]
One PR until end.

**Comment by TobKed** [comment]
All PRs successfully merged.
