### ISSUE TITLE
[AIRFLOW-3511] Create GCP Memorystore Redis Hook

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#123]
Hello,

Here is an ticket related to GCP on Jira:
https://issues.apache.org/jira/browse/AIRFLOW-3511

Lots of love

**Comment by mik-laj** [comment]
Duplicate of: https://github.com/PolideaInternal/airflow/issues/162

**Comment by nuclearpinguin** [comment]
@mik-laj should we close this because of #162?

**Comment by mik-laj** [comment]
Reply here: https://github.com/PolideaInternal/airflow/issues/124#issuecomment-513276800
