### ISSUE TITLE
[AIRFLOW-3512] Create GCP Memorystore Redis Operators

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#124]
Hello,

Here is an ticket related to GCP on Jira:
https://issues.apache.org/jira/browse/AIRFLOW-3512

Love

**Comment by mik-laj** [comment]
Duplicate of: https://github.com/PolideaInternal/airflow/issues/162

**Comment by nuclearpinguin** [comment]
Same here, should we close it because of #162?

**Comment by mik-laj** [comment]
No, because we want to have the correct status in the spreadsheet. We send the spreadsheet to the client, so we must have real information in it.The script for synchronization - GH<=> spreadsheet is very simple and does not understand the complexity of the situation, so it is better to leave this issue open.

 We should think about this issue that this is part of the #162.

**Comment by mik-laj** [comment]
Mentioned spreadsheet: https://docs.google.com/spreadsheets/d/1MASPbcMfrqQll2xTDiwjF1cGM_OmN5UXBCZwCnsaJa4/edit#gid=0
Mentioned script: 
https://github.com/PolideaInternal/airflow-munchkin/blob/master/hack/copy-gh-jira-state.sh

**Comment by nuclearpinguin** [comment]
Understood ✅
