### ISSUE TITLE
[AIRFLOW-3601] update operators to BigQuery to support location

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#125]
Hello,

Here is an ticket related to GCP on Jira:
https://issues.apache.org/jira/browse/AIRFLOW-3601

Lots of love

**Comment by nuclearpinguin** [comment]
Could be related to #140 #139

**Comment by nuclearpinguin** [comment]
I think this could be as a part of retrofitting operators.

**Comment by nuclearpinguin** [comment]
Closed via https://github.com/apache/airflow/pull/6020
