### ISSUE TITLE
[AIRFLOW-3722] Improve BiqQueryHook test coverage

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#126]
Hello,

Here is an ticket related to GCP on Jira:
https://issues.apache.org/jira/browse/AIRFLOW-3722

Love

---

- [x] - [[AIRFLOW-6172] BigQuery - Move BigQuery hook Pandas data frame system tests to separate file](https://github.com/apache/airflow/pull/6729)
- [x] - [[AIRFLOW-6203] BigQuery - parametrize hook tests](https://github.com/apache/airflow/pull/6759)
- [x] - [~~[AIRFLOW-6215] BigQuery - use unittest assertions in hooks tests~~](https://github.com/apache/airflow/pull/6769)
- [x] - [[AIRFLOW-6220] BigQuery - remove redundant hook tests after renaming](https://github.com/apache/airflow/pull/6776)
- [x] - [[AIRFLOW-6223] BigQuery - improve hook tests [depends on AIRFLOW-6220]](https://github.com/apache/airflow/pull/6777)
- [x] - [[AIRLFOW-6240] BigQuery - remove unnecessary mocks in hook system tests](https://github.com/apache/airflow/pull/6805)
- [x] - [[AIRFLOW-6317] BigQuery - move repeated variables to constants in hook tests](https://github.com/apache/airflow/pull/6869)
- [x] - [[AIRFLOW-6314] BigQuery - improve BigQueryHook test](https://github.com/apache/airflow/pull/6865)
- [x] - [[AIRFLOW-6317] BigQuery - move repeated variables to constants in hook tests](https://github.com/apache/airflow/pull/6869)
- [x] - [[AIRFLOW-6403] BigQuery - add tests for BigQueryCursor](https://github.com/apache/airflow/pull/6967)
- [x] - [[AIRFLOW-6409] BigQuery hook - add tests for run_query method](https://github.com/apache/airflow/pull/6971)
- [x] - [~~[AIRFLOW-6408] BigQuery hook - add tests for patch_table method~~](https://github.com/apache/airflow/pull/6972)
- [x] - [~~[AIRFLOW-6407] BigQuery hook - add tests for create_external_table method~~](https://github.com/apache/airflow/pull/6973)
- [x] - [[AIRFLOW-6430] - BigQuery hook - add tests for BigQueryBaseCursor](https://github.com/apache/airflow/pull/7010)
- [x] - [[AIRFLOW-6442] BigQuery hook - standardize handling http exceptions](https://github.com/apache/airflow/pull/7028)
- [x] - [[AIRFLOW-6484] BigQuery hook - standardize handling http exceptions](https://github.com/apache/airflow/pull/7076)
- [x] - [[AIRFLOW-6485] BigQuery hook - add missing tests](https://github.com/apache/airflow/pull/7077)
- [ ] - [[AIRFLOW-6498] BigQuery operator tests - add deprecation tests](https://github.com/apache/airflow/pull/7093)

**Comment by mik-laj** [comment]
We don't do this now, We should rewrite this library to GCP library.

**Comment by TobKed** [comment]
- [x] - [[AIRFLOW-6172] BigQuery - Move BigQuery hook Pandas data frame system tests to separate file](https://github.com/apache/airflow/pull/6729)
- [x] - [[AIRFLOW-6203] BigQuery - parametrize hook tests](https://github.com/apache/airflow/pull/6759)
- [ ] - [[AIRFLOW-6215] BigQuery - use unittest assertions in hooks tests](https://github.com/apache/airflow/pull/6769)
- [ ] - []()
- [ ] - []()

**Comment by TobKed** [comment]
https://issues.apache.org/jira/browse/AIRFLOW-3722 shouldn't be changed to different status?

**Comment by potiuk** [comment]
> https://issues.apache.org/jira/browse/AIRFLOW-3722 shouldn't be changed to different status?
Done! Thanks @TobKed
