### ISSUE TITLE
[AIRFLOW-3804] MySqlToGoogleCloudStorageOperator success when it should fail

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#127]
Hello,

Here is an ticket related to GCP on Jira:
https://issues.apache.org/jira/browse/AIRFLOW-3804

Lots of love

**Comment by nuclearpinguin** [comment]
@potiuk @mik-laj please take a look at the jira issue. I could not replicate the error but I extended tests.

**Comment by nuclearpinguin** [comment]
Closed via https://github.com/apache/airflow/pull/5993
