### ISSUE TITLE
[AIRFLOW-3978] Add missing types in MySqlToGoogleCloudStorageOperator

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#128]
Hello,

Here is an ticket related to GCP on Jira:
https://issues.apache.org/jira/browse/AIRFLOW-3978

Love

**Comment by nuclearpinguin** [comment]
Add BINARY , VARBINARY

**Comment by nuclearpinguin** [comment]
@mik-laj could you take look at the JIRA?

**Comment by mik-laj** [comment]
Let's wait for other people's opinions.
