### ISSUE TITLE
[AIRFLOW-4575] Operators using BigQueryHook need to provide location field

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#140]
Hello,

Here is an ticket related to GCP on Jira:
https://issues.apache.org/jira/browse/AIRFLOW-4575

Love

**Comment by nuclearpinguin** [comment]
Could be related to #136 #137

**Comment by nuclearpinguin** [comment]
Closed via https://github.com/apache/airflow/pull/6020
