### ISSUE TITLE
[AIRFLOW-4583] ERROR - a bytes-like object is required, not 'str' while using gcp_conn_id and python3

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#141]
Hello,

Here is an ticket related to GCP on Jira:
https://issues.apache.org/jira/browse/AIRFLOW-4583

Related community PR:
https://github.com/apache/airflow/pull/5333

Love

**Comment by nuclearpinguin** [comment]
Addressed in https://github.com/apache/airflow/pull/5612
