### ISSUE TITLE
[AIRFLOW-4746] Implement GCP Cloud Tasks' Hook and Operators

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#144]
Hello,

Here is an ticket related to GCP on Jira:
https://issues.apache.org/jira/browse/AIRFLOW-4746

Lots of love

**Comment by nuclearpinguin** [comment]
@mik-laj @potiuk here is a PR waiting for a review
https://github.com/apache/airflow/pull/5402

**Comment by mik-laj** [comment]
Can you do a review too?  all eyes are very helpful.

**Comment by nuclearpinguin** [comment]
Merged!
