### ISSUE TITLE
[AIRFLOW-4771] Initialization of hook in the GCP operator constructors

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#148]
Hello,

Here is an ticket related to GCP on Jira:
https://issues.apache.org/jira/browse/AIRFLOW-4771

Lots of love

**Comment by mik-laj** [comment]
Work started in https://github.com/PolideaInternal/airflow/pull/213

**Comment by nuclearpinguin** [comment]
I opened PR https://github.com/apache/airflow/pull/5893
