### ISSUE TITLE
[AIRFLOW-4774] MLEngineHook should use the built-in Google Discovery API method for retry requests

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#150]
Hello,

Here is an ticket related to GCP on Jira:
https://issues.apache.org/jira/browse/AIRFLOW-4774

Love

**Comment by nuclearpinguin** [comment]
I think it would be best to do this as part of retrofitting. The test imho requires to be refactored.
Anyway, I did some work #212

**Comment by nuclearpinguin** [comment]
As discussed this could not be the best idea. How we proceed with this @mik-laj ?
