### ISSUE TITLE
[AIRFLOW-4970] Add Google Campaign Manager integration

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#158]
Hi

Airflow lacks integration with the Google Campaign Manager service. I would be happy if Airflow had proper operators and hooks that integrate with this service.

Product Documentation: https://developers.google.com/doubleclick-advertisers/
API Documentation: https://github.com/googleapis/google-api-python-client
Jira Ticket: https://issues.apache.org/jira/browse/AIRFLOW-4970

Love

**Comment by nuclearpinguin** [comment]
Work done in #275

**Comment by nuclearpinguin** [comment]
Closed via https://github.com/apache/airflow/pull/6169
