### ISSUE TITLE
[AIRFLOW-4971] Add Google Display & Video 360 integration

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#159]
Hi

Airflow lacks integration with the Google Display & Video 360 service. I would be happy if Airflow had proper operators and hooks that integrate with this service.

Product Documentation: https://developers.google.com/bid-manager/guides/getting-started-api
API Documentation: https://developers.google.com/bid-manager/guides/getting-started-api
Jira Ticket: https://issues.apache.org/jira/browse/AIRFLOW-4971

Lots of love

**Comment by nuclearpinguin** [comment]
Closed via https://github.com/apache/airflow/pull/6170
