### ISSUE TITLE
[AIRFLOW-4972] Add Google Search Ads 360 integration

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#160]
Hi

Airflow lacks integration with the Google Search Ads 360 service. I would be happy if Airflow had proper operators and hooks that integrate with this service.

Product Documentation: https://developers.google.com/search-ads/
API Documentation: https://developers.google.com/resources/api-libraries/documentation/dfareporting/v3.3/python/latest/
Jira Ticket: https://issues.apache.org/jira/browse/AIRFLOW-4972

Love

**Comment by nuclearpinguin** [comment]
Closed via https://github.com/apache/airflow/pull/6228
