### ISSUE TITLE
[AIRFLOW-3511][AIRFLOW-3512] Add Cloud Memorystore integration

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#162]
Hi

Airflow lacks integration with the Cloud Memorystore service. I would be happy if Airflow had proper operators and hooks that integrate with this service.

Product Documentation: https://cloud.google.com/memorystore/docs/redis/
API Documentation: https://googleapis.github.io/google-cloud-python/latest/redis/index.html
Jira Ticket: https://issues.apache.org/jira/browse/AIRFLOW-3512, https://issues.apache.org/jira/browse/AIRFLOW-3511

Love

**Comment by nuclearpinguin** [comment]
Should we close it @mik-laj ?
