### ISSUE TITLE
Retrofit integration guide

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#206]
Hello,

I think, we should retrofit integration guide. 
https://docs.google.com/document/d/1_rTdJSLCt0eyrAylmmgYc3yZr-_h51fVlnvMmWqhCkY/edit?ts=5bb72dfd#
This is out of date. It does not contain the latest practices and recommendations that we use internally during the development of operators. We should prepare updates to this document to be able to update operators in the next step. All recommendations must be collected and written down in one place. Learning to write operators should be based on reading the guide, not on a series of operator reviews with an experienced developer. 

I think we should start thinking about regularly updating this document in response to comments in PR in the community.  It seems to me that the only way to keep one style.

I think that this is the most important thing we should do before we start working on retrofiting.  In my opinion this is a blocker for this phase of the project.

CC: @potiuk @nuclearpinguin

**Comment by potiuk** [comment]
It sounds a bit dramatic - but it is not. This was the purpose of the document from the very beginning and it's just the right time to review it and possibly update the rules.

I agree with all you wrote, but I don't think it's a blocker - it's just part of the task. We should simply make sure we update it according tot the agreements we will have with Feng/David. And it was part of the retrofitting effort from the very beginning. We've learned a few things and 

This has actually been planned already as part of the retrofitting - we even proposed that already in emails and Feng agreed to it :). And we already kept it updated several times in the past.

So nothing new here. I don't think it needs a lot of changes, few naming conventions updated, removing some inconsistencies, adding some new rules. And it will get outdated over time and we will have to fix it in the future as well, it's just the natural lifecycle of such documents. They grow old and need to be updated from time to time (as we as humans tend to forget about updating them regularly, no matter what we agree to do).
