### ISSUE TITLE
Normalize project_id parameter

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#207]
Hello
This parameter is called inconsistently. Sometimes it is called `project`

> To ensure consistency across all GCP operators in Airflow, the following operator parameter names, which apply to most (if not all) services, should be used: 
> * `project_id`: for identifying a GCP project, e.g., “my-project”.
> [...]

**Comment by TobKed** [comment]
Everything looks fine except 'Dataproc' and 'BigQery'. It should be part of separated works.
