### ISSUE TITLE
Normalize location parameter

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#208]
Hi
Sometimes this is passed by the constructor, and sometimes by the method

**Comment by nuclearpinguin** [comment]
Could you provide an example?

**Comment by mik-laj** [comment]
For example:
Class GceHook have method with following deffintion:
```
    def stop_instance(self, zone: str, resource_id: str, project_id: str = None) -> None:
```
We should change the zone parameter to be called location. You need to check each location parameter to see if it is used correctly. Maybe it's worth entering a fallback for the default value from the connection configuration?

**Comment by nuclearpinguin** [comment]
I am not sure if a fallback would be good option. Often resources are in other location that the default and sometimes only, a single location is supported (ex. AutoML).

Regarding naming - I would love to have one param name but it seems that Google itself uses location / region in the same context (ex. [Dataproc](https://googleapis.dev/python/dataproc/latest/_modules/google/cloud/dataproc_v1/gapic/cluster_controller_client.html#ClusterControllerClient.create_cluster) )

**Comment by mik-laj** [comment]
I'm not sure if storage location is a good idea, but it would be helpful. I will think about it longer.

This is a recommendation from the integration guide. 
``
location: region or zone where the GCP resource is to be created/updated/deleted, e.g., “us-central1”.
``

**Comment by nuclearpinguin** [comment]
Playing with GKE operators I had error:
```
google.api_core.exceptions.InvalidArgument: 400 'zone' field cannot be used to access GKE regional clusters. Use 'name' or 'parent' fields instead.
```
when I passed `location='europe-north1'`.  It happens that when creating cluster, user have to pass [zone not region](https://github.com/kubernetes/kubernetes/issues/58736#issuecomment-368189720).  `location='europe-north1-a'` worked.

**Comment by mik-laj** [comment]
This normalization can be misleading for users. Let's leave it as it is now.
