### ISSUE TITLE
Use ParseDict to validate hook input

### ISSUE THREAD

**Issue by nuclearpinguin** [PolideaInternal/airflow#209]
Use  `google.protobuf.json_format.ParseDict` to validate hook body input.
Example:

```python
my config: dict # same as TransferConfig protobuf
parsed config: TransferConfig = ParseDict(my_config, TransferConfig())
```

**Comment by potiuk** [comment]
I think validating locally can be done in __init__ as long as all the parameters are passed in init (this will be "fail-fast" case). We should avoid running DB operations in __init__ but validating params should be pretty OK.

**Comment by nuclearpinguin** [comment]
There's one big argument against it: templated fields. Passing a dictionary with jinja templates may result that verification with ParseDict and proto will fail. We can move the verification step to `execute` but this will not be as fast `fail fast` as it would be in case of doing this in `__init__`.
