### ISSUE TITLE
Add system tests for DataFlow

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#224]

**Comment by nuclearpinguin** [comment]
@mik-laj Dataflow operators are relying on project_id and location from `@GoogleCloudBaseHook.provide_gcp_credential_file`. Should we refactor those operators before system test? It will require changes that can break backward compatibility.

**Comment by nuclearpinguin** [comment]
Or should this be solved by https://github.com/apache/airflow/pull/5907?

**Comment by nuclearpinguin** [comment]
Closed in https://github.com/apache/airflow/pull/6035
