### ISSUE TITLE
Set do_xcom_push in GCP operators

### ISSUE THREAD

**Issue by turbaszek** [PolideaInternal/airflow#259]
Many GCP operators rely on pushing information too xcom. However, the default behaviour is going to be changed and the return value will not be returned to xcom.
https://github.com/apache/airflow/pull/5779

**Comment by potiuk** [comment]
Might be not needed. I think the apache#5779 change should fix all the operators that need it. I made a comment there https://github.com/apache/airflow/pull/5779#issuecomment-538953236

**Comment by nuclearpinguin** [comment]
I agree, the issue was created to not forget about this change.

**Comment by turbaszek** [comment]
Closing as the issue was abandoned and killed by stale bot
