### ISSUE TITLE
Fix FileToGCS operator

### ISSUE THREAD

**Issue by nuclearpinguin** [PolideaInternal/airflow#269]
When I do this:
```   
 upload_file = FileToGoogleCloudStorageOperator(
        task_id="upload_file",
        src='test.txt',
        dst="upload",
        bucket=BUCKET
    )
```
I expect that `test.txt` file will be put under `BUCKET/upload/test.txt` however, nothing happens. Operation succeeds but the file is not uploaded.

However, if I do:
```   
 upload_file = FileToGoogleCloudStorageOperator(
        task_id="upload_file",
        src='test.txt',
        dst="upload/test.txt",
        bucket=BUCKET
    )
```
everything works as expected 🧙🏼‍♂️

**Comment by kaxil** [comment]
I would have expected a file named `upload` in `BUCKET`. GCS is not a filesystem so it won't know if it is a folder/file, they are just objects.

Can you double-check it didn't create a file called `upload` in your 1st case?

**Comment by nuclearpinguin** [comment]
Confirmed, but I make a mistake in example because I thought about:
```
 upload_file = FileToGoogleCloudStorageOperator(
        task_id="upload_file",
        src='test.txt',
        dst="upload/",
        bucket=BUCKET
    )
```
and in this case I would expect that this task will fail or resolve to `upload/test.txt`.

**Comment by kaxil** [comment]
Ok, so the issue is the `dst` parameter is the **full file path to destination object on GCS, including GCS object**. The reason why nothing happened here is `upload/` contains a "slash" which it will try to mimic directory type behavior. It would be like uploading a file as a directory, which won't work, hence you do not see a file.

> Confirmed, but I made a mistake in example because I thought about:
> 
> ```
>  upload_file = FileToGoogleCloudStorageOperator(
>         task_id="upload_file",
>         src='test.txt',
>         dst="upload/",
>         bucket=BUCKET
>     )
> ```
> 
> and in this case I would expect that this task will fail or resolve to `upload/test.txt`.

**Comment by nuclearpinguin** [comment]
I figured it but still it is worth to add nice explanation in docstrings to explain it.

**Comment by kaxil** [comment]
> I figured it but still it is worth to add nice explanation in docstrings to explain it.

Agree

**Comment by nuclearpinguin** [comment]
Closed via https://github.com/apache/airflow/pull/5985
