### ISSUE TITLE
Switch to the Airflow Breeze in the GCP Breeze extension

### ISSUE THREAD

**Issue by potiuk** [PolideaInternal/airflow#284]

**Comment by potiuk** [comment]
@nuclearpinguin @TobKed @mik-laj -> I will also work on this one since Breeze is already merged to master/v1-10-test.

**Comment by nuclearpinguin** [comment]
Can’t wait to test it 💪🏻

**Comment by nuclearpinguin** [comment]
I think we should close this for now. WDYT? Keys can be delivered using files directory

**Comment by potiuk** [comment]
Yep. As longa as we have an easy way to use Breeze for System tests and it's documented/easy - I consider it done.
