### ISSUE TITLE
Introduce pydocstyle

### ISSUE THREAD

**Issue by potiuk** [PolideaInternal/airflow#285]
Introduce pydocstyle in pre-commits to check + keep checked that the documentation we write follows good style of python documentation.

**Comment by potiuk** [comment]
@mik-laj -> I will work on this one while addressing your comments to the docs added in my Airflow Pylint change. I think it's worth to solve documentation style in a systemic way by introducing pydocstyle so that as reviewers we do not have to even worry about it.

**Comment by turbaszek** [comment]
@potiuk @mik-laj should we move this issue to Airflow issues?

**Comment by potiuk** [comment]
https://github.com/apache/airflow/issues/8091 created. Closing this one.
