### ISSUE TITLE
[AIRFLOW-4226] DataProcPySparkOperator gets project ID from gcp_conn_id rather than project_id

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#349]
https://issues.apache.org/jira/browse/AIRFLOW-4226

**Comment by nuclearpinguin** [comment]
I propose to address this as a part of #236 . User should migrate to `DataprocSubmitJob` operator.

**Comment by mik-laj** [comment]
@nuclearpinguin is it done?

**Comment by nuclearpinguin** [comment]
Yes it was addressed in refactor
