### ISSUE TITLE
Consider mocking http request instead of mocking whole library

### ISSUE THREAD

**Issue by turbaszek** [PolideaInternal/airflow#448]
Often in test we mock whole discovery / python client. Maybe we could try to make those test deeper by mocking http requests send by those libraries?

**Comment by mik-laj** [comment]
We use unitest.mock and we test all operators in isolation.

**Comment by mik-laj** [comment]
@turbaszek Do we want to do something about this PR?

**Comment by turbaszek** [comment]
I think we had an internal discussion some time ago and we decided that it would awesome but not worth doing it. Let's close.
