### ISSUE TITLE
Test MySQLOperators on Cloud Composer

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow#625]
![Screenshot from 2020-04-04 12-50-18](https://user-images.githubusercontent.com/595491/78425143-0d057700-7673-11ea-86d6-d924686c9e02.png)

All works with SQL proxies. I have not tested direct  connections but there is no reason it should not work :)

**Comment by mik-laj** [comment]
@potiuk  What is the progress of this task?

**Comment by potiuk** [comment]
Still working on it. I hope to have final answers by today. So far the status is that some ways of connection should work but require complex setup (certificates etc) and some will require change in image configuration most likely (sqlproxy connection is open but the client setting forces SSL). I will likely have some update today on it.
