### ISSUE TITLE
Refactor Operators that export tabular data to GCS

### ISSUE THREAD

**Issue by ANiteckiP** [PolideaInternal/airflow#672]
Currently, we have some code and functionality duplication regarding Operators which export tabular data to GCS, that is `BaseSQLToGCSOperator` and `CassandraToGCSOperator`.
Work-in-progress `GoogleSheetsToGCSOperator` would also need to either duplicate that code, or inherit from `BaseSQLToGCSOperator`.

I propose to extract into a Hook the existing functionality related to data exporting, namely:
- Data serialisation to CSV and JSON formats.
- Writing compressed (gzip) dumps.
- Optional BigQuery schema generation (as requested by user passing optional argument).

This would clean up both the design and implementation of tabular data moving operators - they would work as a simple composition of two hooks, one importing (providing `cursor` - an iterator over rows) and one exporting the rows.
Since BigQuery accepts standard SQL data types in their schemas, this should also work for a common ground for schema generation functionality.

**Comment by mik-laj** [comment]
We don't do that. We have a different solution.
