### ISSUE TITLE
System tests

### ISSUE THREAD

**Issue by potiuk** [PolideaInternal/airflow#679]
https://docs.google.com/spreadsheets/d/1TF7AFx2rmseqlg07Q4ntO9VsnDtNd1_KDF93epjvNVI/edit#gid=0

Remaining:

- [x] Cloud Build
- [x] Cloud Memory Store
- [x] Cloud SQL
- [x] Cloud Storage Transfer
- [x] Compute
- [x] Dataflow
- [x] Postgres
- [x] MySQL

**Comment by nuclearpinguin** [comment]
Do we have any steps that should be followed to run testing of the new packages?
